[package]
name = "rust_test_export"
version = "0.1.0"
edition = "2021"

[dependencies]
libtest-mimic = "0.8.1"
linkme = { version = "0.3"}

[features]
default = []
tests = []

[[bin]]
name = "run_tests"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]
