[package]
name = "somelib"
version = "0.1.0"
edition = "2024"

[dependencies]
libtest-mimic = "0.8"
linkme = "0.3"
satchel = { path = "../../../crates/satchel" }
test-runner = { path = "../../test-runner" }

[lib]
crate-type = ["cdylib"]
